### ISSUE TITLE
Research APIs

### ISSUE THREAD

**Issue by yunko1803** [software-students-fall2021/project-setup-foodwithfriends#66]
Here are a couple of APIs we will _possibly_ use
- [Documenu](https://documenu.com/) Restaurant Menu API --- allows you to filter by cuisine, location, and specific menu items
- [Yelp](https://www.yelp.com/developers/documentation/v3/business_search) Business Search API --- can be used to fetch specific restaurant details and user reviews 
- [Google Maps](https://developers.google.com/maps/documentation) API

Feel free to research other APIs you think we'll need

**Comment by Jen-Lopez** [comment]
API Research doc [here](https://docs.google.com/document/d/1lVYKOjmASushMuUXxjTVUmH9eGimgxErG34n5O4REuo/edit?usp=sharing)
